### ISSUE TITLE
Feature request - variable range

### ISSUE THREAD

**Issue by MikeAgresearch** [Nixola/VRRTest#2]
Sorry, not an issue per se but would it be possible to have an added feature to specify a range of fps that it will auto fluctuate between? Like set 40-60 and it will ramp the FPS up and down? That would make it the perfect test.

**Comment by Nixola** [comment]
Hi! Sorry it took a while to get back to you, Github keeps not notifying me of anything, regardless of how many times I manually watch the repo.  
That said, it should be pretty easy to do but the controls would then get a bit confusing, so I feel I should revamp the UI before adding such a feature. If you have a control scheme that makes sense in mind please do reply (hoping I'll get notified this time).

**Comment by MikeAgresearch** [comment]
Thanks mate, I quite like the UI as it is, and I dont want you to have to do too much work, why not just a button to toggle "variable refresh rate" on or off, and then two more sets of buttons to control the range. Say for example "[" lowers bottom of range value, "]" increases, and then the same for the top of the range value. You could even keep Up/Down so that its just the target FPS when the variable feature is off and then the top of range value when toggled on. I dunno, just an idea, however you wanna do it.

**Comment by Nixola** [comment]
Hi! I changed the keybindings and made a new release. Try it out and let me know if it's good, after which I'll close the issue.

**Comment by MikeAgresearch** [comment]
Love it mate, thank you so much, only thing is, and it may be me, is that I cant seem to change the random stutter amount, using ctrl + +/-, nothing changes.

**Comment by Nixola** [comment]
Fixed that, by changing some keybindings yet again. I was using two modifier keys already, why not three? Four might be pushing it though.

**Comment by MikeAgresearch** [comment]
Thanks man, its perfect, if you have paypal ill shout you a beer.

**Comment by Nixola** [comment]
Sure I do, although I'd rather not write my email in a public issue... I get enough spam as it is
