### ISSUE TITLE
Unable to increase amount of columns in the Bars scene

### ISSUE THREAD

**Issue by brlin-tw** [Nixola/VRRTest#4]
Entering the `+` character(`Shift`+ `=`) doesn't work, though I can decrease the column count by pressing the `-` button on my keyboard.

## Reproducing environment

This section describes the environment where the issue is reproduced:

### Operating system

Ubuntu 24.04

### Love 2D

11.5-1build1 from the Ubuntu 24.04 software archive

### Locale

zh_TW.UTF-8

**Comment by Nixola** [comment]
Fixed, sorry about the oversight. A hotfix release will follow shortly, here's a fixed .love file in the meantime (just rename it to .love); please let me know if you can still reproduce the bug or if you encounter any other issue with this build.
[vrrTest_v2.0.1.zip](https://github.com/user-attachments/files/16081888/vrrTest_v2.0.1.zip)

**Comment by brlin-tw** [comment]
@Nixola Thanks for your prompt fix, I can verify that I can no longer reproduce this issue on the 1532c62 revision.

**Comment by Nixola** [comment]
Great!
